"""Export an AssessmentResult to DOCX or PDF.

Both formats are built from the structured result (title, risk-summary table,
then the seven report sections). Section bodies are markdown; a small block
parser turns them into paragraphs, bullet lists and tables so the documents
render cleanly without depending on a full markdown engine.
"""
from __future__ import annotations

import io
import re

from app.models.schemas import AssessmentResult

# --- Minimal markdown block parser ------------------------------------------
_SEP_CHARS = set("-: ")


def _is_separator(cells: list[str]) -> bool:
    return all(c and set(c) <= _SEP_CHARS for c in cells)


def parse_blocks(md: str) -> list[dict]:
    """Split a markdown body into blocks: para / list / table."""
    lines = md.split("\n")
    blocks: list[dict] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip():
            i += 1
            continue
        if line.strip().startswith("|"):
            rows: list[list[str]] = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                cells = [c.strip() for c in lines[i].strip().strip("|").split("|")]
                if not _is_separator(cells):
                    rows.append(cells)
                i += 1
            blocks.append({"type": "table", "rows": rows})
        elif line.lstrip().startswith("- "):
            items: list[str] = []
            while i < len(lines) and lines[i].lstrip().startswith("- "):
                items.append(lines[i].lstrip()[2:].strip())
                i += 1
            blocks.append({"type": "list", "items": items})
        else:
            para: list[str] = []
            while (i < len(lines) and lines[i].strip()
                   and not lines[i].strip().startswith("|")
                   and not lines[i].lstrip().startswith("- ")):
                para.append(lines[i].strip())
                i += 1
            blocks.append({"type": "para", "text": " ".join(para)})
    return blocks


def _inline_runs(text: str) -> list[tuple[str, bool]]:
    """Split text on **bold** markers into (text, is_bold) runs."""
    runs: list[tuple[str, bool]] = []
    bold = False
    for part in re.split(r"\*\*", text):
        if part:
            runs.append((part, bold))
        bold = not bold
    return runs


# --- DOCX --------------------------------------------------------------------
def to_docx(result: AssessmentResult) -> bytes:
    from docx import Document

    doc = Document()
    doc.add_heading(f"Environmental Impact Assessment — {result.project.name}", level=0)
    meta = doc.add_paragraph(
        f"Screening-level EIA generated by Impatika. Prose generator: {result.report.generator}."
    )
    meta.runs[0].italic = True
    overall = doc.add_paragraph()
    overall.add_run(f"Overall environmental risk: {result.overall_risk.value}").bold = True

    doc.add_heading("Risk summary", level=1)
    table = doc.add_table(rows=1, cols=3)
    table.style = "Table Grid"
    hdr = table.rows[0].cells
    for cell, label in zip(hdr, ("Theme", "Risk", "Basis")):
        cell.text = label
        cell.paragraphs[0].runs[0].bold = True
    for s in result.risk_scores:
        cells = table.add_row().cells
        cells[0].text = s.category
        cells[1].text = s.level.value
        cells[2].text = s.reason

    for section in result.report.sections:
        doc.add_heading(section.title, level=1)
        _render_blocks_docx(doc, parse_blocks(section.body))

    if result.warnings:
        doc.add_heading("Data warnings", level=1)
        for w in result.warnings:
            doc.add_paragraph(w, style="List Bullet")

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _render_blocks_docx(doc, blocks: list[dict]) -> None:
    for block in blocks:
        if block["type"] == "para":
            p = doc.add_paragraph()
            for text, bold in _inline_runs(block["text"]):
                p.add_run(text).bold = bold
        elif block["type"] == "list":
            for item in block["items"]:
                p = doc.add_paragraph(style="List Bullet")
                for text, bold in _inline_runs(item):
                    p.add_run(text).bold = bold
        elif block["type"] == "table":
            rows = block["rows"]
            if not rows:
                continue
            ncols = max(len(r) for r in rows)
            t = doc.add_table(rows=0, cols=ncols)
            t.style = "Table Grid"
            for ri, row in enumerate(rows):
                cells = t.add_row().cells
                for ci in range(ncols):
                    val = (row[ci] if ci < len(row) else "").replace("**", "")
                    cells[ci].text = val
                    if ri == 0 and cells[ci].paragraphs[0].runs:
                        cells[ci].paragraphs[0].runs[0].bold = True


# --- PDF ---------------------------------------------------------------------
_PDF_SUBSTITUTIONS = {
    "—": "-", "–": "-", "°": " deg", "≈": "~", "→": "->", "•": "-",
    "’": "'", "‘": "'", "“": '"', "”": '"', "…": "...",
}


def _pdf_text(text: str) -> str:
    for src, dst in _PDF_SUBSTITUTIONS.items():
        text = text.replace(src, dst)
    return text.encode("latin-1", "replace").decode("latin-1")


def to_pdf(result: AssessmentResult) -> bytes:
    from fpdf import FPDF
    from fpdf.enums import XPos, YPos

    pdf = FPDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    pdf.multi_cell(0, 8, _pdf_text(f"Environmental Impact Assessment — {result.project.name}"),
                   new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(110)
    pdf.multi_cell(0, 5, _pdf_text(f"Screening-level EIA generated by Impatika. Prose generator: {result.report.generator}."),
                   new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0)
    pdf.ln(1)
    pdf.set_font("Helvetica", "B", 12)
    pdf.multi_cell(0, 7, _pdf_text(f"Overall environmental risk: {result.overall_risk.value}"),
                   new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 13)
    pdf.multi_cell(0, 7, "Risk summary", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    risk_rows = [["Theme", "Risk", "Basis"]] + [[s.category, s.level.value, s.reason] for s in result.risk_scores]
    _render_table_pdf(pdf, risk_rows, col_widths=(32, 22, 126))

    for section in result.report.sections:
        pdf.ln(3)
        pdf.set_font("Helvetica", "B", 13)
        pdf.multi_cell(0, 7, _pdf_text(section.title), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        _render_blocks_pdf(pdf, parse_blocks(section.body))

    return bytes(pdf.output())


def _render_blocks_pdf(pdf, blocks: list[dict]) -> None:
    from fpdf.enums import XPos, YPos

    pdf.set_font("Helvetica", "", 10)
    for block in blocks:
        if block["type"] == "para":
            pdf.multi_cell(0, 5, _pdf_text(block["text"]), markdown=True,
                           new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.ln(1)
        elif block["type"] == "list":
            for item in block["items"]:
                pdf.multi_cell(0, 5, _pdf_text("- " + item), markdown=True,
                               new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.ln(1)
        elif block["type"] == "table":
            _render_table_pdf(pdf, block["rows"])
            pdf.ln(1)


def _render_table_pdf(pdf, rows: list[list[str]], col_widths=None) -> None:
    if not rows:
        return
    clean = [[_pdf_text(c.replace("**", "")) for c in row] for row in rows]
    pdf.set_font("Helvetica", "", 9)
    kwargs = {"first_row_as_headings": True}
    if col_widths:
        kwargs["col_widths"] = col_widths
    with pdf.table(**kwargs) as table:
        for row in clean:
            trow = table.row()
            for cell in row:
                trow.cell(cell)
    pdf.set_font("Helvetica", "", 10)
