"""Orchestrates the full Impatika assessment (spec steps 1–7).

    project -> AOI -> layers -> metrics -> risk scores -> EIA report -> result
"""
from __future__ import annotations

from shapely.geometry import Point

from app.core import aoi as aoi_mod
from app.core import geo, metrics as metrics_mod, report as report_mod, scoring
from app.core.data_layers import LayerStore, load_layers
from app.models.schemas import AssessmentResult, ProjectInput, RiskLevel


def _base_geometry(project: ProjectInput):
    if project.geometry is not None:
        return geo.to_shape(project.geometry)
    if project.location is not None:
        return Point(project.location.lon, project.location.lat)
    raise ValueError("Project must include either a `location` or a GeoJSON `geometry`.")


def render_markdown(result: AssessmentResult) -> str:
    p = result.project
    lines = [
        f"# Environmental Impact Assessment — {p.name}",
        "",
        f"*Screening-level EIA generated by Impatika. Prose generator: **{result.report.generator}**.*",
        "",
        f"**Overall environmental risk: {result.overall_risk.value}**",
        "",
        "## Risk summary",
        "",
        "| Theme | Risk | Basis |",
        "|---|---|---|",
    ]
    for s in result.risk_scores:
        reason = s.reason.replace("|", "\\|")
        lines.append(f"| {s.category} | {s.level.value} | {reason} |")
    lines.append("")
    if result.warnings:
        lines.append("> **Data warnings:** " + "; ".join(result.warnings))
        lines.append("")
    for section in result.report.sections:
        lines.append(f"## {section.title}")
        lines.append("")
        lines.append(section.body)
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def run_assessment(project: ProjectInput, layers: LayerStore | None = None) -> AssessmentResult:
    layers = layers or load_layers()
    base_geom = _base_geometry(project)

    aoi = aoi_mod.build_aoi(project)
    aoi_geom = geo.to_shape(aoi.geometry)

    metrics = metrics_mod.compute_metrics(aoi_geom, base_geom, project, layers)
    scores, overall = scoring.score(metrics)
    report = report_mod.generate_report(project, aoi, metrics, scores, overall)

    warnings: list[str] = []
    missing = layers.unavailable_names()
    if missing:
        warnings.append(f"Environmental layers unavailable: {', '.join(missing)}. Affected themes scored as Unknown.")

    result = AssessmentResult(
        project=project,
        aoi=aoi,
        metrics=metrics,
        risk_scores=scores,
        overall_risk=overall,
        report=report,
        markdown="",  # filled below once the result object exists
        warnings=warnings,
    )
    result.markdown = render_markdown(result)
    return result
